version: '3'
services:
  comparto-libros:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '9232:9232'
      - '9233:9233'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    container_name: backend_comparto_libros
    environment:
      NODE_ENV: 'development'
      NODE_PORT: 9232
      HOSTNAME: 'localhost'
networks:
  default:
    external:
      name: comparto_libros
